version: '3.5'

services:
  db:
    container_name: postgres-banco-caqui
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/data/postgres

  app:
    container_name: app-banco-caqui
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "npm run migration:run && npm run start"
    volumes:
      - .:/app