version: '3.5'

services:
  db:
    container_name: postgres-banco-caqui
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/data/postgres

